### ISSUE TITLE
issue building

### ISSUE THREAD

**Issue by kamidrills** [verlox/Lithium-Nuker-2#10]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Core' could not be found (are you missing a using directive or an assembly reference?)	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Roles.cs	26	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Channels.cs	13	Active
Error	CS0246	The type or namespace name 'Core' could not be found (are you missing a using directive or an assembly reference?)	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Channels.cs	25	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Roles.cs	13	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Users.cs	14	Active
Error	CS0246	The type or namespace name 'Core' could not be found (are you missing a using directive or an assembly reference?)	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Users.cs	26	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Webhooks.cs	13	Active
Error	CS0246	The type or namespace name 'Core' could not be found (are you missing a using directive or an assembly reference?)	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Webhooks.cs	32	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Entry.cs	12	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Entry.cs	13	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Entry.cs	14	Active
Error	CS0246	The type or namespace name 'Core' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Entry.cs	30	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Picker.cs	11	Active
Error	CS0246	The type or namespace name 'LithiumCore' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Picker.cs	12	Active
Error	CS0246	The type or namespace name 'Core' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Picker.cs	18	Active
Error	CS0246	The type or namespace name 'Channels' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Picker.cs	21	Active
Error	CS0246	The type or namespace name 'Webhooks' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Picker.cs	22	Active
Error	CS0246	The type or namespace name 'Users' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Picker.cs	23	Active
Error	CS0246	The type or namespace name 'Roles' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Picker.cs	24	Active
Error	CS0246	The type or namespace name 'Bot' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Picker.cs	25	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Shared.cs	11	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Shared.cs	12	Active
Error	CS0246	The type or namespace name 'Veylib' could not be found (are you missing a using directive or an assembly reference?)	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Shared.cs	13	Active
Warning	CS7035	The specified version string does not conform to the recommended format - major.minor.build.revision	LithiumCore	C:\Users\.\Desktop\lithium_fresh\LithiumCoreFramework\Properties\AssemblyInfo.cs	36	Active
Warning	CS7035	The specified version string does not conform to the recommended format - major.minor.build.revision	LithiumNukerV2	C:\Users\.\Desktop\lithium_fresh\LithiumNukerV2\Properties\AssemblyInfo.cs	36	Active
Warning		The referenced component 'Veylib' could not be found.	LithiumCore			
Warning		Could not resolve this reference. Could not locate the assembly "Veylib". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	LithiumCore			
Warning		Could not resolve this reference. Could not locate the assembly "Veylib". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	LithiumNukerV2			
Warning		The referenced component 'LithiumCore' could not be found.	LithiumNukerV2			
Warning		The referenced component 'Veylib' could not be found.	LithiumNukerV2			
Warning		Could not resolve this reference. Could not locate the assembly "LithiumCore". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	LithiumNukerV2

**Comment by verlox** [comment]
download and import an older version of veylib [here](https://github.com/verlox/Veylib/releases/tag/v2)
